package:
  name: iolabs
  version: "3.2"

source:
  fn: ioLabs-3.2.tar.gz
  url: https://pypi.python.org/packages/source/i/ioLabs/ioLabs-3.2.tar.gz
  md5: 7e2cff3e57118a04c8c36d7e6d0d34ce
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - iolabs = iolabs:main
    #
    # Would create an entry point called iolabs that calls iolabs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - hid

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.ioLab.co.uk/
  license: UNKNOWN
  summary: 'ioLab response box library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
