package:
  name: pyxid
  version: "1.0"

source:
  fn: pyxid-1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyxid/pyxid-1.0.tar.gz
  md5: e86e89d2413e489d4480b47c8f78ef32
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyxid = pyxid:main
    #
    # Would create an entry point called pyxid that calls pyxid.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyserial >=2.5

  run:
    - python
    - pyserial >=2.5

test:
  # Python imports
  imports:
    - pyxid

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.github.com/cedrus-opensource/pyxid/
  license: BSD License
  summary: 'Pure python library for communicating with Cedrus XID and StimTracker devices.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
