package:
  name: pyhocon
  version: "0.3.17"

source:
  fn: pyhocon-0.3.17.tar.gz
  url: https://pypi.python.org/packages/source/p/pyhocon/pyhocon-0.3.17.tar.gz
  md5: 568532e96a3962fd8e51a3a28b06d65d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyhocon = pyhocon:main
    #
    # Would create an entry point called pyhocon that calls pyhocon.main()

    - pyhocon=pyhocon.tool:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyparsing ==2.0.3

  run:
    - python
    - pyparsing ==2.0.3

test:
  # Python imports
  imports:
    - pyhocon

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pyhocon --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache Software License
  summary: 'HOCON parser for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
