package:
  name: pysoundcard
  version: "0.5.2"

source:
  fn: PySoundCard-0.5.2.tar.gz
  url: https://pypi.python.org/packages/source/P/PySoundCard/PySoundCard-0.5.2.tar.gz
  md5: d0bce4c0fe19cba235fd73516f61a19e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysoundcard = pysoundcard:main
    #
    # Would create an entry point called pysoundcard that calls pysoundcard.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cffi >=0.6

  run:
    - python
    - numpy
    - cffi >=0.6

about:
  home: https://github.com/bastibe/PySoundCard
  license: BSD License
  summary: 'An audio library based on PortAudio, CFFI and NumPy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
