package:
  name: pysoundfile
  version: "0.8.1"

source:
  fn: PySoundFile-0.8.1.tar.gz
  url: https://pypi.python.org/packages/source/P/PySoundFile/PySoundFile-0.8.1.tar.gz
  md5: 276f26f454848ce7abcf5155c64e7680
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysoundfile = pysoundfile:main
    #
    # Would create an entry point called pysoundfile that calls pysoundfile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cffi >=0.6

  run:
    - python
    - cffi >=0.6


about:
  home: https://github.com/bastibe/PySoundFile
  license: BSD License
  summary: 'An audio library based on libsndfile, CFFI and NumPy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
