package:
  name: bdist_mpkg
  version: "0.5.0"

source:
  fn: bdist_mpkg-0.5.0.tar.gz
  url: https://pypi.python.org/packages/source/b/bdist_mpkg/bdist_mpkg-0.5.0.tar.gz
  md5: 81f5f8601331acda2926efeb97a0804d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bdist_mpkg = bdist_mpkg:main
    #
    # Would create an entry point called bdist_mpkg that calls bdist_mpkg.main()

    - bdist_mpkg = bdist_mpkg.script_bdist_mpkg:main
    - reown_mpkg = bdist_mpkg.script_reown_mpkg:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - bdist_mpkg

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    #- bdist_mpkg --help
    #- reown_mpkg --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/matthew-brett/bdist_mpkg
  license: MIT License
  summary: 'Builds Mac OS X installer packages from distutils'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
